### ISSUE TITLE
Channel info not always updated properly on system start

### ISSUE THREAD

**Issue by surfacescan** [FarmRadioHangar/fessbox#131]
When all dongles configured properly they don't always appear properly on restart.

Sometimes it displays "unknown" for the number
Sometimes it shows no operator info, sometimes it shows operator info properly.

![screenshot from 2017-04-13 07-03-28](https://cloud.githubusercontent.com/assets/7801564/24989751/88842ab2-2017-11e7-8ea1-b1fd562d3e8a.png)

A good old fashioned `systemctl restart fessbox` fixes the issue:

![screenshot from 2017-04-13 07-06-02](https://cloud.githubusercontent.com/assets/7801564/24989773/ae74db36-2017-11e7-9981-af1cc5636f1f.png)

My guess is that fessbox is sending the channel state to the UI too early, before the network info and sim state etc has been properly set/determined.

**Comment by surfacescan** [comment]
@miopa +1 for prioritising this issue.  It is confusing to people when they restart their voxbox becuase at the moment it shows unknown number and does not show network indicator so ppl think there is no network on their modems when all is needed is a fessbox restart.

Thanks man

**Comment by surfacescan** [comment]
Nice - what was the issue?
Have you managed to push the update and test on the deployed boxes?

**Comment by miopa** [comment]
Because of a mistake in the service file, fessbox started before asterisk. https://github.com/FarmRadioHangar/fessbox/commit/6a12b69c99ace4ab05e69fd69c40c02a4d8e0b80

In theory even this should not matter, but that part of the code is a mess and updates are not working properly in some cases. I'll tackle that issue when I get to refactoring.

I pushed the new service file, it's working (nobody complained :)
